services:
  planetscale-proxy:
    image: ghcr.io/mattrobenolt/ps-http-sim:latest
    command:
      [
        "-listen-port=3900",
        "-mysql-dbname=defaultdb",
        "-mysql-addr=mysql-7abd75f-rsd1701-6b62.a.aivencloud.com",
        "-mysql-port=28146",
      ]
    ports:
      - 3900:3900
